services:
  homebridge:
    image: ghcr.io/sethicis/portainer-stack-homelab:latest
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
    volumes:
      - /home/sethicis/compose/homebridge/homebridge:/homebridge:z
    configs:
      - source: sleep_script
        target: /hb-scripts/sleep.sh
        mode: 0555
      - source: status_script
        target: /hb-scripts/status.sh
        mode: 0555
      - source: wake_script
        target: /hb-scripts/wake.sh
        mode: 0555
  scrypted:
    environment:
      # Scrypted NVR Storage (Part 2 of 3)

      # Uncomment the next line to configure the NVR plugin to store recordings
      # use the /nvr directory within the container. This can also be configured
      # within the plugin manually.
      # The drive or network share will ALSO need to be configured in the volumes
      # section below.
      - SCRYPTED_NVR_VOLUME=/nvr

      - SCRYPTED_WEBHOOK_UPDATE_AUTHORIZATION=Bearer QfCaljRjYf6PhYBMQxo0B0X0Wl8RVj6V
      - SCRYPTED_WEBHOOK_UPDATE=http://localhost:10444/v1/update

      # Uncomment next line to run avahi-daemon inside the container
      # Don't use if dbus and avahi run on the host and are bind-mounted
      # (see below under "volumes")
      - SCRYPTED_DOCKER_AVAHI=true
      - "TZ=America/Chicago"

      # Uncomment next 3 lines for Nvidia GPU support.
      # - NVIDIA_VISIBLE_DEVICES=all
      # - NVIDIA_DRIVER_CAPABILITIES=all
      # runtime: nvidia

    volumes:
      # Scrypted NVR Storage (Part 3 of 3)

      # Modify to add the additional volume for Scrypted NVR.
      # The following example would mount the /mnt/sda/video path on the host
      # to the /nvr path inside the docker container.
      - nvr:/nvr

      # Or use a network mount from one of the CIFS/NFS examples at the top of this file.
      # - type: volume
      #   source: nvr
      #   target: /nvr
      #   volume:
      #     nocopy: true

      # uncomment the following lines to expose Avahi, an mDNS advertiser.
      # make sure Avahi is running on the host machine, otherwise this will not work.
      # not compatible with Avahi enabled via SCRYPTED_DOCKER_AVAHI=true
      # - /var/run/dbus:/var/run/dbus
      # - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

      # Default volume for the Scrypted database. Typically should not be changed.
      - config:/server/volume
    devices: [
      # uncomment the common systems devices to pass
      # them through to docker.

      # all usb devices, such as coral tpu
      # "/dev/bus/usb:/dev/bus/usb",

      # hardware accelerated video decoding, opencl, etc.
      "/dev/dri:/dev/dri"

      # uncomment below as necessary.
      # zwave usb serial device

      # "/dev/ttyACM0:/dev/ttyACM0",

      # coral PCI devices
      # "/dev/apex_0:/dev/apex_0",
      # "/dev/apex_1:/dev/apex_1",
    ]

    container_name: scrypted
    restart: unless-stopped
    network_mode: host
    image: ghcr.io/koush/scrypted:v0.144.3-noble-full

    # logging is noisy and will unnecessarily wear on flash storage.
    # scrypted has per device in memory logging that is preferred.
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

configs:
  sleep_script:
    content: |
      #!/usr/bin/env bash
      curl http://$WOL_LOGIN@$WOL_MACHINE:$WOL_PORT/sleep
  status_script:
    content: |
      #!/usr/bin/env bash
      result=$(curl -s -o /dev/null -i -w "%{http_code}" -m 1 http://$WOL_LOGIN@$WOL_MACHINE:$WOL_PORT/state/local)
      echo $result
  wake_script:
    content: |
      #!/usr/bin/env bash
      etherwake -i eno1 $WOL_MAC_ADDRESS

volumes:
  nvr:
    driver_opts:
      type: "nfs"
      o: "addr=172.16.0.154,nolock,soft,rw,nfsvers=4"
      device: ":/volume1/public/nvr"
  config:
    driver_opts:
      type: "nfs"
      o: "addr=172.16.0.154,nolock,soft,rw,nfsvers=4"
      device: ":/volume1/content/scrypted"
