name: Portainer GitOps Update

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  deployments: write
  id-token: write

concurrency:
  cancel-in-progress: true
  group: gitops-${{github.ref}}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  should_build:
    runs-on: ubuntu-latest
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            docker:
              - 'Dockerfile'
              - 'docker-compose.yml'
  build-docker-image:
    runs-on: ubuntu-latest
    needs: should_build
    if: ${{ needs.should_build.outputs.docker == 'true' || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v6
      - name: Check for Dockerfile
        run: |
          if [ ! -f './Dockerfile' ]; then
            exit 1
          fi
          ## Carry on
          exit 0
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v7.2.0
        with:
          context: .
          # Path to the Dockerfile
          file: ./Dockerfile
          # List of target platforms for build
          # platforms: # optional
          push: true
          tags: ${{ steps.meta.outputs.tags }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
  trigger-portainer:
    needs: build-docker-image
    runs-on: ubuntu-latest
    # If the hook is defined, run the job, otherwise skip
    if: ${{ !failure() }}
    steps:
      - name: Trigger Portainer webhook
        run: |
          curl --fail --show-error --silent --request POST "${{ secrets.PORTAINER_HOOK }}"
